### ISSUE TITLE
Error occurs when attempting to launch server/server.py even after installing from requirements.txt

### ISSUE THREAD

**Issue by nicholastmosher** [wastevensv/intercom#2]
Traceback (most recent call last):
  File "server/server.py", line 10, in <module>
    from twisted.protocols.basic import LineReceiver
ImportError: No module named 'twisted'

After executing the following:
sudo pip install -r requirements.txt
sudo apt-get install python-dev
python3 server/server.py

**Comment by sherrardTr4129** [comment]
I think this is because you are using pip where pip3 should be used. pip is for python 2.

Try: 
sudo pip3 install -r requirements.txt
sudo apt-get install python-dev
python3 server/server.py

**Comment by nicholastmosher** [comment]
I think you guys need to add espeak to your list of requirements.  Is espeak installed using pip?

nick@Obsidyn:~/Documents/intercom$ python3 client/client.py 
connecting to: localhost
Connected successfully
1444757272.323289 New Message Recieved:  Hello how is everyone
'Hello how is everyone'
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(_call.args, *_call.kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/task.py", line 213, in **call**
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(_args, *_kw)
  File "client/client.py", line 16, in check
    cmd.act()
  File "/home/nick/Documents/intercom/client/plugins/command.py", line 36, in act
    subprocess.call(["espeak", self.text])
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(_popenargs, *_kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
builtins.FileNotFoundError: [Errno 2] No such file or directory: 'espeak'

**Comment by sherrardTr4129** [comment]
you have to do:
sudo apt-get install espeak.

**Comment by sherrardTr4129** [comment]
I added this to the README.

**Comment by sherrardTr4129** [comment]
I'm going to close this issue as i feel like that script really fixed this problem. Thanks!
